# Generated by Django 6.0.1 on 2026-01-11 16:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('stream_url', models.URLField(blank=True, help_text='URL for video stream')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(help_text='Source camera or video identifier', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='detections/')),
                ('video', models.FileField(blank=True, null=True, upload_to='detections/videos/')),
                ('confidence_score', models.FloatField(help_text='AI confidence score (0-1)')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed Violence'), ('false_positive', 'False Positive')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about the detection')),
                ('location', models.CharField(blank=True, help_text='Physical location where violence was detected', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='detection_d_timesta_bff5ba_idx'), models.Index(fields=['status'], name='detection_d_status_d902cc_idx'), models.Index(fields=['severity'], name='detection_d_severit_124994_idx')],
            },
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_time', models.FloatField(help_text='Time taken to process in seconds')),
                ('frames_analyzed', models.IntegerField(default=0)),
                ('violence_detected', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.monitoringcamera')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
